/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

/**
 *
 * @author angel
 */
public class Ventana extends javax.swing.JFrame {
    
    SAX gesSAX = new SAX();
    XPath gesxPath = new XPath();
    
    Añadir ventanaAñadir = new Añadir(this);

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAMostrar = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAConsulta = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMItemMostrar = new javax.swing.JMenuItem();
        jMItemGuardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMItemAñadir = new javax.swing.JMenuItem();
        jMItemModificar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMItemTamaño = new javax.swing.JMenuItem();
        jMItemMateriales = new javax.swing.JMenuItem();
        jMItemPrecio = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAMostrar.setColumns(20);
        jTextAMostrar.setRows(5);
        jScrollPane1.setViewportView(jTextAMostrar);

        jTextAConsulta.setColumns(20);
        jTextAConsulta.setRows(5);
        jScrollPane2.setViewportView(jTextAConsulta);

        jMenu1.setText("Archivo");

        jMItemMostrar.setText("Mostrar");
        jMItemMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemMostrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMItemMostrar);

        jMItemGuardar.setText("Guardar");
        jMenu1.add(jMItemGuardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMItemAñadir.setText("Añadir");
        jMItemAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemAñadirActionPerformed(evt);
            }
        });
        jMenu2.add(jMItemAñadir);

        jMItemModificar.setText("Modificar");
        jMenu2.add(jMItemModificar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultas");

        jMItemTamaño.setText("Tamaño");
        jMItemTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemTamañoActionPerformed(evt);
            }
        });
        jMenu3.add(jMItemTamaño);

        jMItemMateriales.setText("Materiales");
        jMItemMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemMaterialesActionPerformed(evt);
            }
        });
        jMenu3.add(jMItemMateriales);

        jMItemPrecio.setText("Precio");
        jMItemPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemPrecioActionPerformed(evt);
            }
        });
        jMenu3.add(jMItemPrecio);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMItemMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemMostrarActionPerformed
        if (gesSAX.abrirXML_SAX()){
            jLabel1.setText("XML mostrado perfectamente");
            jTextAMostrar.setText(gesSAX.recorrerSAX());
        }
        else{
            jLabel1.setText("Error al cargar el XML");   
        }
    }//GEN-LAST:event_jMItemMostrarActionPerformed

    private void jMItemAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemAñadirActionPerformed
        ventanaAñadir.setVisible(true);
    }//GEN-LAST:event_jMItemAñadirActionPerformed

    private void jMItemTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemTamañoActionPerformed
        jTextAConsulta.setText(gesxPath.ejecutaXPath("/Muebles/*/Tamaño"));
    }//GEN-LAST:event_jMItemTamañoActionPerformed

    private void jMItemMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemMaterialesActionPerformed
        jTextAConsulta.setText(gesxPath.ejecutaXPath("/Muebles/Mueble/Tamaño"));
    }//GEN-LAST:event_jMItemMaterialesActionPerformed

    private void jMItemPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemPrecioActionPerformed
        jTextAConsulta.setText(gesxPath.ejecutaXPath("/Muebles/Mueble/Tamaño"));
    }//GEN-LAST:event_jMItemPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMItemAñadir;
    private javax.swing.JMenuItem jMItemGuardar;
    private javax.swing.JMenuItem jMItemMateriales;
    private javax.swing.JMenuItem jMItemModificar;
    private javax.swing.JMenuItem jMItemMostrar;
    private javax.swing.JMenuItem jMItemPrecio;
    private javax.swing.JMenuItem jMItemTamaño;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAConsulta;
    private javax.swing.JTextArea jTextAMostrar;
    // End of variables declaration//GEN-END:variables
}
